// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module QGPMuxLayer(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:188:7
  input  [31:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_2_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_2_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_3_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_3_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_4_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_4_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_5_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_5_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
  input  [2:0]  io_in_sel,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
  output [31:0] io_out_QSV_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_out_QSV_1	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
);

  wire [7:0][31:0] _GEN =
    {{io_in_QSV_0_0},
     {io_in_QSV_0_0},
     {io_in_QSV_5_0},
     {io_in_QSV_4_0},
     {io_in_QSV_3_0},
     {io_in_QSV_2_0},
     {io_in_QSV_1_0},
     {io_in_QSV_0_0}};	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:195:15
  wire [7:0][31:0] _GEN_0 =
    {{io_in_QSV_0_1},
     {io_in_QSV_0_1},
     {io_in_QSV_5_1},
     {io_in_QSV_4_1},
     {io_in_QSV_3_1},
     {io_in_QSV_2_1},
     {io_in_QSV_1_1},
     {io_in_QSV_0_1}};	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:195:15
  assign io_out_QSV_0 = _GEN[io_in_sel];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:188:7, :195:15
  assign io_out_QSV_1 = _GEN_0[io_in_sel];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:188:7, :195:15
endmodule

module No_op(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:22:7
  input  [31:0] io_in_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:23:14
                io_in_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:23:14
  output [31:0] io_out_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:23:14
                io_out_1	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:23:14
);

  assign io_out_0 = io_in_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:22:7
  assign io_out_1 = io_in_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:22:7
endmodule

module Pauli_X(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:36:7
  input  [31:0] io_in_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:37:14
                io_in_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:37:14
  output [31:0] io_out_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:37:14
                io_out_1	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:37:14
);

  assign io_out_0 = io_in_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:36:7
  assign io_out_1 = io_in_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:36:7
endmodule

module turnNegative(	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\flipMSB\\turnNegative.scala:11:7
  input  [15:0] io_in,	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\flipMSB\\turnNegative.scala:12:14
  output [15:0] io_out	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\flipMSB\\turnNegative.scala:12:14
);

  assign io_out = {(|(io_in[14:0])) & ~(io_in[15]), io_in[14:0]};	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\flipMSB\\turnNegative.scala:11:7, :16:{16,22,30,42,48,56}
endmodule

module Pauli_Y(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:52:7
  input  [31:0] io_in_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:53:14
                io_in_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:53:14
  output [31:0] io_out_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:53:14
                io_out_1	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:53:14
);

  wire [15:0] _flipD_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:59:21
  wire [15:0] _flipA_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:58:21
  turnNegative flipA (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:58:21
    .io_in  (io_in_0[31:16]),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:61:26
    .io_out (_flipA_io_out)
  );
  turnNegative flipD (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:59:21
    .io_in  (io_in_1[15:0]),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:62:26
    .io_out (_flipD_io_out)
  );
  assign io_out_0 = {_flipD_io_out, io_in_1[31:16]};	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:52:7, :59:21, :65:{19,42}
  assign io_out_1 = {io_in_0[15:0], _flipA_io_out};	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:52:7, :58:21, :66:{19,28}
endmodule

module Pauli_Z(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:76:7
  input  [31:0] io_in_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:77:14
                io_in_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:77:14
  output [31:0] io_out_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:77:14
                io_out_1	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:77:14
);

  wire [15:0] _flipD_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:83:21
  wire [15:0] _flipC_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:82:21
  turnNegative flipC (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:82:21
    .io_in  (io_in_1[31:16]),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:84:26
    .io_out (_flipC_io_out)
  );
  turnNegative flipD (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:83:21
    .io_in  (io_in_1[15:0]),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:85:26
    .io_out (_flipD_io_out)
  );
  assign io_out_0 = io_in_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:76:7
  assign io_out_1 = {_flipC_io_out, _flipD_io_out};	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:76:7, :82:21, :83:21, :89:29
endmodule

module S_gate(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:103:7
  input  [31:0] io_in_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:104:14
                io_in_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:104:14
  output [31:0] io_out_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:104:14
                io_out_1	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:104:14
);

  wire [15:0] _flipD_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:108:21
  turnNegative flipD (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:108:21
    .io_in  (io_in_1[15:0]),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:109:26
    .io_out (_flipD_io_out)
  );
  assign io_out_0 = io_in_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:103:7
  assign io_out_1 = {_flipD_io_out, io_in_1[31:16]};	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:103:7, :108:21, :113:{29,40}
endmodule

module InverseS_gate(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:123:7
  input  [31:0] io_in_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:124:14
                io_in_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:124:14
  output [31:0] io_out_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:124:14
                io_out_1	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:124:14
);

  wire [15:0] _flipC_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:128:21
  turnNegative flipC (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:128:21
    .io_in  (io_in_1[31:16]),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:129:26
    .io_out (_flipC_io_out)
  );
  assign io_out_0 = io_in_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:123:7
  assign io_out_1 = {io_in_1[15:0], _flipC_io_out};	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGates.scala:123:7, :128:21, :133:{24,37}
endmodule

module AcceleratedGatePool(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
  input         clock,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
                reset,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
  input  [31:0] io_in_QSV_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:31:14
                io_in_QSV_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:31:14
  input  [3:0]  io_in_sel,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:31:14
  input         io_in_valid,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:31:14
  output [31:0] io_out_QSV_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:31:14
                io_out_QSV_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:31:14
  output        io_out_valid	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:31:14
);

  wire [31:0] _InverseSGate_0_io_out_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:109:67
  wire [31:0] _InverseSGate_0_io_out_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:109:67
  wire [31:0] _SGate_0_io_out_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:97:60
  wire [31:0] _SGate_0_io_out_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:97:60
  wire [31:0] _pauliZ_0_io_out_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:86:61
  wire [31:0] _pauliZ_0_io_out_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:86:61
  wire [31:0] _pauliY_0_io_out_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:75:61
  wire [31:0] _pauliY_0_io_out_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:75:61
  wire [31:0] _pauliX_0_io_out_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:64:61
  wire [31:0] _pauliX_0_io_out_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:64:61
  wire [31:0] _no_op_0_io_out_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:53:60
  wire [31:0] _no_op_0_io_out_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:53:60
  reg         io_out_valid_r;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:180:32
  always @(posedge clock)	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
    io_out_valid_r <= io_in_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:180:32
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
        io_out_valid_r = _RANDOM[/*Zero width*/ 1'b0][0];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7, :180:32
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  QGPMuxLayer muxLayer (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:48:31
    .io_in_QSV_0_0 (_no_op_0_io_out_0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:53:60
    .io_in_QSV_0_1 (_no_op_0_io_out_1),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:53:60
    .io_in_QSV_1_0 (_pauliX_0_io_out_0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:64:61
    .io_in_QSV_1_1 (_pauliX_0_io_out_1),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:64:61
    .io_in_QSV_2_0 (_pauliY_0_io_out_0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:75:61
    .io_in_QSV_2_1 (_pauliY_0_io_out_1),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:75:61
    .io_in_QSV_3_0 (_pauliZ_0_io_out_0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:86:61
    .io_in_QSV_3_1 (_pauliZ_0_io_out_1),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:86:61
    .io_in_QSV_4_0 (_SGate_0_io_out_0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:97:60
    .io_in_QSV_4_1 (_SGate_0_io_out_1),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:97:60
    .io_in_QSV_5_0 (_InverseSGate_0_io_out_0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:109:67
    .io_in_QSV_5_1 (_InverseSGate_0_io_out_1),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:109:67
    .io_in_sel     (io_in_sel[2:0]),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:49:23
    .io_out_QSV_0  (io_out_QSV_0),
    .io_out_QSV_1  (io_out_QSV_1)
  );
  No_op no_op_0 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:53:60
    .io_in_0  (io_in_QSV_0),
    .io_in_1  (io_in_QSV_1),
    .io_out_0 (_no_op_0_io_out_0),
    .io_out_1 (_no_op_0_io_out_1)
  );
  Pauli_X pauliX_0 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:64:61
    .io_in_0  (io_in_QSV_0),
    .io_in_1  (io_in_QSV_1),
    .io_out_0 (_pauliX_0_io_out_0),
    .io_out_1 (_pauliX_0_io_out_1)
  );
  Pauli_Y pauliY_0 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:75:61
    .io_in_0  (io_in_QSV_0),
    .io_in_1  (io_in_QSV_1),
    .io_out_0 (_pauliY_0_io_out_0),
    .io_out_1 (_pauliY_0_io_out_1)
  );
  Pauli_Z pauliZ_0 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:86:61
    .io_in_0  (io_in_QSV_0),
    .io_in_1  (io_in_QSV_1),
    .io_out_0 (_pauliZ_0_io_out_0),
    .io_out_1 (_pauliZ_0_io_out_1)
  );
  S_gate SGate_0 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:97:60
    .io_in_0  (io_in_QSV_0),
    .io_in_1  (io_in_QSV_1),
    .io_out_0 (_SGate_0_io_out_0),
    .io_out_1 (_SGate_0_io_out_1)
  );
  InverseS_gate InverseSGate_0 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:109:67
    .io_in_0  (io_in_QSV_0),
    .io_in_1  (io_in_QSV_1),
    .io_out_0 (_InverseSGate_0_io_out_0),
    .io_out_1 (_InverseSGate_0_io_out_1)
  );
  assign io_out_valid = io_out_valid_r;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:30:7, :180:32
endmodule

