// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module full_adder(	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:78:9
  input  [4:0] io_in_a,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:79:16
               io_in_b,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:79:16
  output [4:0] io_out_s,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:79:16
  output       io_out_c	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:79:16
);

  wire [5:0] result = {1'h0, io_in_a} + {1'h0, io_in_b};	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:87:23
  assign io_out_s = result[4:0];	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:78:9, :87:23, :88:23
  assign io_out_c = result[5];	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:78:9, :87:23, :89:23
endmodule

module multiplier(	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:106:9
  input  [10:0] io_in_a,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:107:16
                io_in_b,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:107:16
  output [21:0] io_out_s	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:107:16
);

  assign io_out_s = {11'h0, io_in_a} * {11'h0, io_in_b};	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:106:9, :113:23
endmodule

module FP_mult_16_1_v2(	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
  input         clock,	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
  input  [15:0] io_in_a,	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:153:16
                io_in_b,	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:153:16
  output [15:0] io_out_s	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:153:16
);

  wire [21:0] _multiplier_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:239:33
  wire [4:0]  _exp_adder_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:228:27
  wire        _exp_adder_io_out_c;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:228:27
  wire [4:0]  exp_wire_1 =
    (&(io_in_b[14:10])) ? 5'h1E : io_in_b[14:10] == 5'h0 ? 5'h1 : io_in_b[14:10];	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:192:33, :194:36, :199:{14,33,44}, :200:19, :201:{36,46}, :202:19, :204:19, :259:74
  wire        uo_check = exp_wire_1 < 5'hF;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:199:44, :200:19, :201:46, :230:38, :250:69
  wire [5:0]  _o_flag_reg_T_1 =
    {1'h0, _exp_adder_io_out_s} + {5'h0, _multiplier_io_out_s[21]};	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9, :228:27, :239:33, :254:51, :259:74
  wire        u_flag_reg = uo_check & (~_exp_adder_io_out_c | _o_flag_reg_T_1 == 6'h0);	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:228:27, :250:69, :259:{39,49,61,74,95}
  wire        o_flag_reg = ~uo_check & (_exp_adder_io_out_c | _o_flag_reg_T_1 > 6'h1E);	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:228:27, :250:69, :259:74, :260:{39,40,61,95}
  wire [9:0]  out_frac =
    u_flag_reg
      ? 10'h0
      : o_flag_reg
          ? 10'h3FF
          : _multiplier_io_out_s[21]
              ? _multiplier_io_out_s[20:11]
              : _multiplier_io_out_s[19:10];	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:239:33, :254:51, :259:39, :260:39, :269:{46,108,162}, :277:48, :283:23
  reg  [15:0] io_out_s_r;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:288:55
  always @(posedge clock)	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
    io_out_s_r <=
      {io_in_a[15] ^ io_in_b[15],
       u_flag_reg
         ? 5'h1
         : o_flag_reg
             ? 5'h1E
             : _multiplier_io_out_s[21]
                 ? _exp_adder_io_out_s + 5'h1
                 : _exp_adder_io_out_s,
       out_frac};	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:181:25, :182:25, :192:33, :194:36, :222:33, :228:27, :239:33, :254:51, :259:39, :260:39, :268:{45,105}, :276:47, :282:22, :283:23, :288:{55,76}
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
        io_out_s_r = _RANDOM[/*Zero width*/ 1'b0][15:0];	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9, :288:55
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  full_adder exp_adder (	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:228:27
    .io_in_a
      ((&(io_in_a[14:10])) ? 5'h1E : io_in_a[14:10] == 5'h0 ? 5'h1 : io_in_a[14:10]),	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:192:{14,33,44}, :193:19, :194:{36,46}, :195:19, :197:19, :259:74
    .io_in_b  (exp_wire_1 - 5'hF),	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:199:44, :200:19, :201:46, :230:38
    .io_out_s (_exp_adder_io_out_s),
    .io_out_c (_exp_adder_io_out_c)
  );
  multiplier multiplier (	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:239:33
    .io_in_a  ({1'h1, io_in_a[9:0]}),	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9, :209:25, :214:31
    .io_in_b  ({1'h1, io_in_b[9:0]}),	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9, :210:25, :215:31
    .io_out_s (_multiplier_io_out_s)
  );
  assign io_out_s =
    io_in_a[14:0] == 15'h0 | io_in_b[14:0] == 15'h0
      ? 16'h0
      : io_out_s_r + {15'h0, io_in_a == io_in_b | (&out_frac)};	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:150:9, :283:23, :285:{30,40,44,55,65}, :286:{30,42,54}, :288:{25,55,110}
endmodule

module full_subtractor(	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:92:9
  input  [4:0] io_in_a,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:93:16
               io_in_b,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:93:16
  output [4:0] io_out_s,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:93:16
  output       io_out_c	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:93:16
);

  wire [5:0] result = {1'h0, io_in_a} - {1'h0, io_in_b};	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:101:23
  assign io_out_s = result[4:0];	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:92:9, :101:23, :102:23
  assign io_out_c = result[5];	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:92:9, :101:23, :103:23
endmodule

module full_adder_4(	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:78:9
  input  [10:0] io_in_a,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:79:16
                io_in_b,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:79:16
  output [10:0] io_out_s,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:79:16
  output        io_out_c	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:79:16
);

  wire [11:0] result = {1'h0, io_in_a} + {1'h0, io_in_b};	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:87:23
  assign io_out_s = result[10:0];	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:78:9, :87:23, :88:23
  assign io_out_c = result[11];	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:78:9, :87:23, :89:23
endmodule

module LZC_enc2(	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:8:9
  input  [1:0] io_in_r,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:9:16
  output [1:0] io_out_e	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:9:16
);

  assign io_out_e = io_in_r == 2'h0 ? 2'h2 : {1'h0, io_in_r == 2'h1};	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:8:9, :24:48, src/main/scala/chisel3/util/Mux.scala:126:16
endmodule

module LZC_Merge2(	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:63:9
  input  [1:0] io_in_h,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:64:16
               io_in_l,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:64:16
  output [2:0] io_out_m	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:64:16
);

  assign io_out_m =
    {io_in_h[1] & io_in_l[1],
     io_in_h[1] ? ~(io_in_l[1]) : io_in_h[1],
     io_in_h[1] ? io_in_l[0] : io_in_h[0]};	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:63:9, :72:{27,34,43}, :73:{23,46}, :74:{20,50,67}, :75:33
endmodule

module LZC_Merge3(	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:63:9
  input  [2:0] io_in_h,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:64:16
               io_in_l,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:64:16
  output [3:0] io_out_m	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:64:16
);

  assign io_out_m =
    {io_in_h[2] & io_in_l[2],
     io_in_h[2] ? ~(io_in_l[2]) : io_in_h[2],
     io_in_h[2] ? io_in_l[1:0] : io_in_h[1:0]};	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:63:9, :72:{27,34,43}, :73:{23,46}, :74:{20,50,67}, :75:33
endmodule

module LZC_Merge4(	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:63:9
  input  [3:0] io_in_h,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:64:16
               io_in_l,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:64:16
  output [4:0] io_out_m	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:64:16
);

  assign io_out_m =
    {io_in_h[3] & io_in_l[3],
     io_in_h[3] ? ~(io_in_l[3]) : io_in_h[3],
     io_in_h[3] ? io_in_l[2:0] : io_in_h[2:0]};	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:63:9, :72:{27,34,43}, :73:{23,46}, :74:{20,50,67}, :75:33
endmodule

module LZC16_2(	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:30:9
  input  [15:0] io_in_d,	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:31:16
  output [4:0]  io_out_c	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:31:16
);

  wire [3:0] _LZC_Merge3_1_io_out_m;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
  wire [3:0] _LZC_Merge3_io_out_m;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
  wire [2:0] _LZC_Merge2_3_io_out_m;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
  wire [2:0] _LZC_Merge2_2_io_out_m;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
  wire [2:0] _LZC_Merge2_1_io_out_m;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
  wire [2:0] _LZC_Merge2_io_out_m;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
  wire [1:0] _LZC_enc2_7_io_out_e;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
  wire [1:0] _LZC_enc2_6_io_out_e;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
  wire [1:0] _LZC_enc2_5_io_out_e;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
  wire [1:0] _LZC_enc2_4_io_out_e;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
  wire [1:0] _LZC_enc2_3_io_out_e;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
  wire [1:0] _LZC_enc2_2_io_out_e;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
  wire [1:0] _LZC_enc2_1_io_out_e;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
  wire [1:0] _LZC_enc2_io_out_e;	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
  LZC_enc2 LZC_enc2 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_r  (io_in_d[1:0]),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:38:27
    .io_out_e (_LZC_enc2_io_out_e)
  );
  LZC_enc2 LZC_enc2_1 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_r  (io_in_d[3:2]),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:38:27
    .io_out_e (_LZC_enc2_1_io_out_e)
  );
  LZC_enc2 LZC_enc2_2 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_r  (io_in_d[5:4]),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:38:27
    .io_out_e (_LZC_enc2_2_io_out_e)
  );
  LZC_enc2 LZC_enc2_3 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_r  (io_in_d[7:6]),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:38:27
    .io_out_e (_LZC_enc2_3_io_out_e)
  );
  LZC_enc2 LZC_enc2_4 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_r  (io_in_d[9:8]),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:38:27
    .io_out_e (_LZC_enc2_4_io_out_e)
  );
  LZC_enc2 LZC_enc2_5 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_r  (io_in_d[11:10]),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:38:27
    .io_out_e (_LZC_enc2_5_io_out_e)
  );
  LZC_enc2 LZC_enc2_6 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_r  (io_in_d[13:12]),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:38:27
    .io_out_e (_LZC_enc2_6_io_out_e)
  );
  LZC_enc2 LZC_enc2_7 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_r  (io_in_d[15:14]),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:38:27
    .io_out_e (_LZC_enc2_7_io_out_e)
  );
  LZC_Merge2 LZC_Merge2 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_in_h  (_LZC_enc2_7_io_out_e),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_l  (_LZC_enc2_6_io_out_e),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_out_m (_LZC_Merge2_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_1 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_in_h  (_LZC_enc2_5_io_out_e),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_l  (_LZC_enc2_4_io_out_e),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_out_m (_LZC_Merge2_1_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_2 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_in_h  (_LZC_enc2_3_io_out_e),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_l  (_LZC_enc2_2_io_out_e),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_out_m (_LZC_Merge2_2_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_3 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_in_h  (_LZC_enc2_1_io_out_e),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_in_l  (_LZC_enc2_io_out_e),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:36:50
    .io_out_m (_LZC_Merge2_3_io_out_m)
  );
  LZC_Merge3 LZC_Merge3 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_in_h  (_LZC_Merge2_io_out_m),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_in_l  (_LZC_Merge2_1_io_out_m),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_out_m (_LZC_Merge3_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_1 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_in_h  (_LZC_Merge2_2_io_out_m),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_in_l  (_LZC_Merge2_3_io_out_m),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_out_m (_LZC_Merge3_1_io_out_m)
  );
  LZC_Merge4 LZC_Merge4 (	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_in_h  (_LZC_Merge3_io_out_m),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_in_l  (_LZC_Merge3_1_io_out_m),	// \\src\\main\\scala\\FloatingPointUnit\\New_Binary_Mario\\BinaryDesignsNew.scala:46:37
    .io_out_m (io_out_c)
  );
endmodule

module FP_add_16_1(	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
  input         clock,	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
                io_in_en,	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:297:16
  input  [15:0] io_in_a,	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:297:16
                io_in_b,	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:297:16
  output [15:0] io_out_s	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:297:16
);

  wire [4:0]  _LZC16_2_io_out_c;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:414:26
  wire [10:0] _full_adder_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:396:28
  wire        _full_adder_io_out_c;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:396:28
  wire [4:0]  _exp_subtractor_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:369:32
  wire        _exp_subtractor_io_out_c;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:369:32
  wire [4:0]  exp_wire_0 =
    {1'h0, io_in_a[14:10]} > 6'h1E
      ? 5'h1E
      : io_in_a[14:10] == 5'h0 ? 5'h1 : io_in_a[14:10];	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9, :339:{14,33,61,68}, :340:19, :341:{36,42}, :342:19, :344:19, :429:137, :430:98
  wire [4:0]  exp_wire_1 =
    {1'h0, io_in_b[14:10]} > 6'h1E
      ? 5'h1E
      : io_in_b[14:10] == 5'h0 ? 5'h1 : io_in_b[14:10];	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9, :339:61, :341:36, :346:{14,33,68}, :347:19, :348:{36,42}, :349:19, :351:19, :429:137, :430:98
  wire        eqexp_arrange = exp_wire_0 == exp_wire_1 & io_in_b[9:0] > io_in_a[9:0];	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:339:68, :340:19, :341:42, :346:68, :347:19, :348:42, :356:25, :357:25, :380:{42,54,88}
  wire        _GEN = _exp_subtractor_io_out_c | eqexp_arrange;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:369:32, :380:42, :389:41
  wire [10:0] fracadd_in_b =
    _exp_subtractor_io_out_c
      ? {1'h1, io_in_a[9:0]} >> ~_exp_subtractor_io_out_s + 5'h1
      : {1'h1, eqexp_arrange ? io_in_a[9:0] : io_in_b[9:0]} >> _exp_subtractor_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9, :356:25, :357:25, :361:31, :369:32, :380:42, :388:67, :390:{41,85,115,155}, :429:137
  wire        diff_sign = io_in_a[15] ^ io_in_b[15];	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:334:25, :335:25, :393:48
  reg  [40:0] norm_out_frac_r;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:435:39
  reg  [4:0]  norm_out_exp;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:440:37
  reg         norm_out_sign;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:444:38
  always @(posedge clock) begin	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
    if (io_in_en) begin	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:297:16
      automatic logic [4:0]  ref_exp = _exp_subtractor_io_out_c ? exp_wire_1 : exp_wire_0;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:339:68, :340:19, :341:42, :346:68, :347:19, :348:42, :369:32, :391:36
      automatic logic [5:0]  _GEN_0 = {1'h0, ref_exp};	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9, :391:36, :423:25
      automatic logic [5:0]  red = _GEN_0 - {1'h0, _LZC16_2_io_out_c};	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9, :414:26, :423:25
      automatic logic [5:0]  inc = _GEN_0 + 6'h1;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:388:92, :423:25, :424:25
      automatic logic [40:0] _GEN_1 = {31'h0, _full_adder_io_out_s[9:0]};	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:396:28, :426:{38,56}
      automatic logic        _innermux_exp_true_T_2 = red == 6'h0;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:390:85, :423:25, :429:137
      automatic logic        _innermux_exp_false_T_2 = inc > 6'h1E;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:339:61, :424:25, :430:98
      norm_out_frac_r <=
        diff_sign
          ? (_full_adder_io_out_s[10]
               ? _GEN_1
               : red[5] | _innermux_exp_true_T_2 ? 41'h0 : _GEN_1 << _LZC16_2_io_out_c)
          : {31'h0,
             _full_adder_io_out_c
               ? (inc[5] | _innermux_exp_false_T_2 ? 10'h3FF : _full_adder_io_out_s[10:1])
               : _full_adder_io_out_s[9:0]};	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:393:48, :396:28, :414:26, :423:25, :424:25, :426:{38,56}, :429:{47,62,114,118,129,137}, :430:{48,75,79,90,98,134}, :435:{39,43}
      norm_out_exp <=
        diff_sign
          ? (_full_adder_io_out_s[10]
               ? ref_exp
               : red[5] | _innermux_exp_true_T_2 ? 5'h1 : red[4:0])
          : _full_adder_io_out_c
              ? (inc[5] | _innermux_exp_false_T_2 ? 5'h1E : inc[4:0])
              : ref_exp;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:391:36, :393:48, :396:28, :423:25, :424:25, :429:{62,118,137}, :430:{79,98}, :431:{46,94,109,141}, :432:{47,74,89,121}, :440:{37,41}
      norm_out_sign <=
        diff_sign
        & (_exp_subtractor_io_out_c
             ? ~_exp_subtractor_io_out_s + 5'h1
             : _exp_subtractor_io_out_s) < 5'hB & ~_full_adder_io_out_c
        ^ (_GEN ? io_in_b[15] : io_in_a[15]);	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:334:25, :335:25, :369:32, :388:{41,67,92,116}, :389:41, :392:37, :393:48, :396:28, :408:{37,80}, :429:137, :444:38
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
      automatic logic [31:0] _RANDOM[0:1];	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
        end	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
        norm_out_frac_r = {_RANDOM[1'h0], _RANDOM[1'h1][8:0]};	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9, :435:39
        norm_out_exp = _RANDOM[1'h1][13:9];	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9, :435:39, :440:37
        norm_out_sign = _RANDOM[1'h1][14];	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9, :435:39, :444:38
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  full_subtractor exp_subtractor (	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:369:32
    .io_in_a  (exp_wire_0),	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:339:68, :340:19, :341:42
    .io_in_b  (exp_wire_1),	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:346:68, :347:19, :348:42
    .io_out_s (_exp_subtractor_io_out_s),
    .io_out_c (_exp_subtractor_io_out_c)
  );
  full_adder_4 full_adder (	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:396:28
    .io_in_a  ({1'h1, _GEN ? io_in_b[9:0] : io_in_a[9:0]}),	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9, :356:25, :357:25, :389:41
    .io_in_b  (diff_sign ? ~fracadd_in_b + 11'h1 : fracadd_in_b),	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:390:41, :393:48, :398:{27,47,69}
    .io_out_s (_full_adder_io_out_s),
    .io_out_c (_full_adder_io_out_c)
  );
  LZC16_2 LZC16_2 (	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:414:26
    .io_in_d  ({_full_adder_io_out_s, 5'h1F}),	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:396:28, :415:{35,82}
    .io_out_c (_LZC16_2_io_out_c)
  );
  assign io_out_s =
    io_in_a[14:0] == 15'h0 & io_in_b[14:0] == 15'h0
      ? 16'h0
      : {norm_out_sign, norm_out_exp, norm_out_frac_r[9:0]};	// \\src\\main\\scala\\FloatingPointUnit\\New_FPU_Mario\\FPUnits.scala:294:9, :435:39, :438:30, :440:37, :444:38, :446:{30,39,43,54,63}, :449:{25,72}
endmodule

module complex_conjugate_mult(	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
  input         clock,	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
                reset,	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
  input  [31:0] io_complexA,	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:31:14
                io_complexB,	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:31:14
  input         io_in_valid,	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:31:14
  output        io_out_valid,	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:31:14
  output [31:0] io_out_s	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:31:14
);

  wire [15:0] _FP_adder_Inst_1_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:70:41
  wire [15:0] _FP_adder_Inst_0_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:70:41
  wire [15:0] _FP_mult_inst_3_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:62:40
  wire [15:0] _FP_mult_inst_2_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:62:40
  wire [15:0] _FP_mult_inst_1_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:62:40
  wire [15:0] _FP_mult_inst_0_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:62:40
  reg  [7:0]  counter;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:50:24
  reg         io_out_valid_r;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:107:32
  reg         io_out_valid_r_1;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:107:32
  always @(posedge clock) begin	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
    if (reset)	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
      counter <= 8'h0;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:50:24
    else	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
      counter <= counter + 8'h1;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:50:24, :54:24, :100:30
    io_out_valid_r <= io_in_valid;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:107:32
    io_out_valid_r_1 <= io_out_valid_r;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:107:32
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
        counter = _RANDOM[/*Zero width*/ 1'b0][7:0];	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7, :50:24
        io_out_valid_r = _RANDOM[/*Zero width*/ 1'b0][8];	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7, :50:24, :107:32
        io_out_valid_r_1 = _RANDOM[/*Zero width*/ 1'b0][9];	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7, :50:24, :107:32
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FP_mult_16_1_v2 FP_mult_inst_0 (	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:62:40
    .clock    (clock),
    .io_in_a  (io_complexA[31:16]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:77:41
    .io_in_b  (io_complexB[31:16]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:78:41
    .io_out_s (_FP_mult_inst_0_io_out_s)
  );
  FP_mult_16_1_v2 FP_mult_inst_1 (	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:62:40
    .clock    (clock),
    .io_in_a  (io_complexA[15:0]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:79:41
    .io_in_b  (io_complexB[15:0]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:80:41
    .io_out_s (_FP_mult_inst_1_io_out_s)
  );
  FP_mult_16_1_v2 FP_mult_inst_2 (	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:62:40
    .clock    (clock),
    .io_in_a  (io_complexA[15:0]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:79:41
    .io_in_b  (io_complexB[31:16]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:78:41
    .io_out_s (_FP_mult_inst_2_io_out_s)
  );
  FP_mult_16_1_v2 FP_mult_inst_3 (	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:62:40
    .clock    (clock),
    .io_in_a  (io_complexA[31:16]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:77:41
    .io_in_b  (io_complexB[15:0]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:80:41
    .io_out_s (_FP_mult_inst_3_io_out_s)
  );
  FP_add_16_1 FP_adder_Inst_0 (	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:70:41
    .clock    (clock),
    .io_in_en (|counter),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:50:24, :100:30
    .io_in_a  ((|counter) ? _FP_mult_inst_0_io_out_s : 16'h0),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:50:24, :62:40, :86:34, :100:30
    .io_in_b  ((|counter) ? _FP_mult_inst_1_io_out_s ^ 16'h8000 : 16'h0),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:50:24, :62:40, :86:34, :87:{34,87}, :100:30
    .io_out_s (_FP_adder_Inst_0_io_out_s)
  );
  FP_add_16_1 FP_adder_Inst_1 (	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:70:41
    .clock    (clock),
    .io_in_en (|counter),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:50:24, :100:30
    .io_in_a  ((|counter) ? _FP_mult_inst_2_io_out_s : 16'h0),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:50:24, :62:40, :86:34, :89:34, :100:30
    .io_in_b  ((|counter) ? _FP_mult_inst_3_io_out_s : 16'h0),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:50:24, :62:40, :86:34, :90:34, :100:30
    .io_out_s (_FP_adder_Inst_1_io_out_s)
  );
  assign io_out_valid = io_out_valid_r_1;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7, :107:32
  assign io_out_s = {_FP_adder_Inst_0_io_out_s, _FP_adder_Inst_1_io_out_s};	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:30:7, :70:41, :106:18
endmodule

module complex_adder(	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
  input         clock,	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
  input  [31:0] io_complexA,	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:127:14
                io_complexB,	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:127:14
  input         io_in_valid,	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:127:14
  output        io_out_valid,	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:127:14
  output [31:0] io_out_s	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:127:14
);

  wire [15:0] _FP_adder_Inst_1_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:140:41
  wire [15:0] _FP_adder_Inst_0_io_out_s;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:140:41
  reg         io_out_valid_r;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:163:32
  always @(posedge clock)	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
    io_out_valid_r <= io_in_valid;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:163:32
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
        io_out_valid_r = _RANDOM[/*Zero width*/ 1'b0][0];	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7, :163:32
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FP_add_16_1 FP_adder_Inst_0 (	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:140:41
    .clock    (clock),
    .io_in_en (1'h1),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
    .io_in_a  (io_complexA[31:16]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:148:42
    .io_in_b  (io_complexB[31:16]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:149:42
    .io_out_s (_FP_adder_Inst_0_io_out_s)
  );
  FP_add_16_1 FP_adder_Inst_1 (	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:140:41
    .clock    (clock),
    .io_in_en (1'h1),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7
    .io_in_a  (io_complexA[15:0]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:150:42
    .io_in_b  (io_complexB[15:0]),	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:151:42
    .io_out_s (_FP_adder_Inst_1_io_out_s)
  );
  assign io_out_valid = io_out_valid_r;	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7, :163:32
  assign io_out_s = {_FP_adder_Inst_0_io_out_s, _FP_adder_Inst_1_io_out_s};	// \\src\\main\\scala\\FloatingPointUnit\\Complex_FPU\\complex.scala:126:7, :140:41, :160:18
endmodule

module AndGate(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:204:7
  input  io_in_valid_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:205:14
         io_in_valid_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:205:14
  output io_out_valid	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:205:14
);

  assign io_out_valid = io_in_valid_0 & io_in_valid_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:204:7, :212:40
endmodule

module FPUPool(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:28:7
  input         clock,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:28:7
                reset,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:28:7
  input  [31:0] io_in_QSV_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
                io_in_QSV_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
                io_in_Ugate_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
                io_in_Ugate_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
                io_in_Ugate_2,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
                io_in_Ugate_3,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
                io_in_normalize,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
  input  [3:0]  io_in_sel,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
  input         io_in_valid,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
  output        io_out_valid,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
  output [31:0] io_out_QSV_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
                io_out_QSV_1	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:30:14
);

  wire        _FPUAdder_1_io_out_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:160:66
  wire        _FPUAdder_0_io_out_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:160:66
  wire        _FPUMultiplier_3_io_out_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
  wire [31:0] _FPUMultiplier_3_io_out_s;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
  wire        _FPUMultiplier_2_io_out_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
  wire [31:0] _FPUMultiplier_2_io_out_s;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
  wire        _FPUMultiplier_1_io_out_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
  wire [31:0] _FPUMultiplier_1_io_out_s;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
  wire        _FPUMultiplier_0_io_out_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
  wire [31:0] _FPUMultiplier_0_io_out_s;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
  wire        _FPUInput3_T = io_in_sel == 4'h0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44
  wire        _FPUInput3_T_2 = io_in_sel == 4'h1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44
  wire        _FPUInput3_T_4 = io_in_sel == 4'h2;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44
  wire        _FPUInput3_T_6 = io_in_sel == 4'h3;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44
  wire        _GEN = _FPUInput3_T_6 | _FPUInput3_T_4;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44
  wire        _FPUInput3_T_8 = io_in_sel == 4'h4;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44
  wire        _FPUInput3_T_10 = io_in_sel == 4'h5;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44
  wire        _GEN_0 = _FPUInput3_T_10 | _FPUInput3_T_8;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44
  wire        _FPUInput3_T_12 = io_in_sel == 4'h6;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44
  complex_conjugate_mult FPUMultiplier_0 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
    .clock        (clock),
    .reset        (reset),
    .io_complexA  (io_in_QSV_0),
    .io_complexB
      (_FPUInput3_T_12
         ? io_in_Ugate_0
         : _GEN_0
             ? 32'h3C000000
             : _GEN
                 ? 32'h38003800
                 : _FPUInput3_T_2
                     ? 32'h39A80000
                     : _FPUInput3_T ? io_in_normalize : 32'h0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44
    .io_in_valid  (io_in_valid),
    .io_out_valid (_FPUMultiplier_0_io_out_valid),
    .io_out_s     (_FPUMultiplier_0_io_out_s)
  );
  complex_conjugate_mult FPUMultiplier_1 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
    .clock        (clock),
    .reset        (reset),
    .io_complexA  (io_in_QSV_1),
    .io_complexB
      (_FPUInput3_T_12
         ? io_in_Ugate_1
         : _GEN_0
             ? 32'h0
             : _FPUInput3_T_6
                 ? 32'hB800B800
                 : _FPUInput3_T_4 ? 32'h3800B800 : _FPUInput3_T_2 ? 32'h39A80000 : 32'h0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44, :135:44
    .io_in_valid  (io_in_valid),
    .io_out_valid (_FPUMultiplier_1_io_out_valid),
    .io_out_s     (_FPUMultiplier_1_io_out_s)
  );
  complex_conjugate_mult FPUMultiplier_2 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
    .clock        (clock),
    .reset        (reset),
    .io_complexA  (io_in_QSV_0),
    .io_complexB
      (_FPUInput3_T_12
         ? io_in_Ugate_2
         : _GEN_0 ? 32'h0 : _GEN ? 32'h38003800 : _FPUInput3_T_2 ? 32'h39A80000 : 32'h0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44, :142:44
    .io_in_valid  (io_in_valid),
    .io_out_valid (_FPUMultiplier_2_io_out_valid),
    .io_out_s     (_FPUMultiplier_2_io_out_s)
  );
  complex_conjugate_mult FPUMultiplier_3 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
    .clock        (clock),
    .reset        (reset),
    .io_complexA  (io_in_QSV_1),
    .io_complexB
      (_FPUInput3_T_12
         ? io_in_Ugate_3
         : _FPUInput3_T_10
             ? 32'h39A8B9A8
             : _FPUInput3_T_8
                 ? 32'h39A839A8
                 : _FPUInput3_T_6
                     ? 32'hB800B800
                     : _FPUInput3_T_4
                         ? 32'h3800B800
                         : _FPUInput3_T_2
                             ? 32'hB9A80000
                             : _FPUInput3_T ? io_in_normalize : 32'h0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:128:44, :135:44, :149:44
    .io_in_valid  (io_in_valid),
    .io_out_valid (_FPUMultiplier_3_io_out_valid),
    .io_out_s     (_FPUMultiplier_3_io_out_s)
  );
  complex_adder FPUAdder_0 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:160:66
    .clock        (clock),
    .io_complexA  (_FPUMultiplier_0_io_out_s),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
    .io_complexB  (_FPUMultiplier_1_io_out_s),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
    .io_in_valid  (_FPUMultiplier_0_io_out_valid & _FPUMultiplier_1_io_out_valid),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68, :190:75
    .io_out_valid (_FPUAdder_0_io_out_valid),
    .io_out_s     (io_out_QSV_0)
  );
  complex_adder FPUAdder_1 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:160:66
    .clock        (clock),
    .io_complexA  (_FPUMultiplier_2_io_out_s),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
    .io_complexB  (_FPUMultiplier_3_io_out_s),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68
    .io_in_valid  (_FPUMultiplier_2_io_out_valid & _FPUMultiplier_3_io_out_valid),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:159:68, :191:75
    .io_out_valid (_FPUAdder_1_io_out_valid),
    .io_out_s     (io_out_QSV_1)
  );
  AndGate FPUvalid (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:161:29
    .io_in_valid_0 (_FPUAdder_0_io_out_valid),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:160:66
    .io_in_valid_1 (_FPUAdder_1_io_out_valid),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FPUGatePool\\Matrix\\FPUGatePool.scala:160:66
    .io_out_valid  (io_out_valid)
  );
endmodule

