// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Fixed16BitAdder(	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
  input  [15:0] io_in_0,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:24:14
                io_in_1,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:24:14
  output [15:0] io_out	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:24:14
);

  reg [15:0] reg_0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:29:22
  always @(posedge clock) begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    if (reset)	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      reg_0 <= 16'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:29:22
    else	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      reg_0 <= io_in_0 - io_in_1;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:29:22, :30:25
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
        reg_0 = _RANDOM[/*Zero width*/ 1'b0][15:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7, :29:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out = reg_0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7, :29:22
endmodule

module Fixed16BitAdder_1(	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
  input  [15:0] io_in_0,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:9:14
                io_in_1,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:9:14
  output [15:0] io_out	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:9:14
);

  reg [15:0] reg_0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:14:22
  always @(posedge clock) begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    if (reset)	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      reg_0 <= 16'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:14:22
    else	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      reg_0 <= io_in_0 + io_in_1;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:14:22, :15:25
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
        reg_0 = _RANDOM[/*Zero width*/ 1'b0][15:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7, :14:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out = reg_0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7, :14:22
endmodule

module Fixed16BitMultiplier(	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
  input  [15:0] io_in_0,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:39:14
                io_in_1,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:39:14
  output [15:0] io_out	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:39:14
);

  reg [15:0] outreg;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:51:23
  always @(posedge clock) begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
    if (reset)	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
      outreg <= 16'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:51:23
    else begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
      automatic logic [29:0] _wireout_T =
        {{14{io_in_0[15]}}, io_in_0} * {{14{io_in_1[15]}}, io_in_1};	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:47:24, :48:24, :49:20
      outreg <= _wireout_T[29:14];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:49:20, :51:23, :52:20
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
        outreg = _RANDOM[/*Zero width*/ 1'b0][15:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7, :51:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out = outreg;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:37:7, :51:23
endmodule

module FixedComplexMultiplier(	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:46:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:46:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:46:7
  input  [15:0] io_in_a_0,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:47:14
                io_in_a_1,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:47:14
  output [15:0] io_out_0,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:47:14
                io_out_1	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:47:14
);

  wire [15:0] _Multiplier_3_io_out;	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
  wire [15:0] _Multiplier_2_io_out;	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
  wire [15:0] _Multiplier_1_io_out;	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
  wire [15:0] _Multiplier_0_io_out;	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
  Fixed16BitAdder Subber (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:52:27
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (_Multiplier_0_io_out),	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
    .io_in_1 (_Multiplier_1_io_out),	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
    .io_out  (io_out_0)
  );
  Fixed16BitAdder_1 Adder (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:53:27
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (_Multiplier_2_io_out),	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
    .io_in_1 (_Multiplier_3_io_out),	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
    .io_out  (io_out_1)
  );
  Fixed16BitMultiplier Multiplier_0 (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_a_0),
    .io_in_1 (16'h2D41),	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:47:14, :54:39
    .io_out  (_Multiplier_0_io_out)
  );
  Fixed16BitMultiplier Multiplier_1 (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_a_1),
    .io_in_1 (16'h0),	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:47:14, :54:39
    .io_out  (_Multiplier_1_io_out)
  );
  Fixed16BitMultiplier Multiplier_2 (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_a_0),
    .io_in_1 (16'h0),	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:47:14, :54:39
    .io_out  (_Multiplier_2_io_out)
  );
  Fixed16BitMultiplier Multiplier_3 (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:54:39
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_a_1),
    .io_in_1 (16'h2D41),	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:47:14, :54:39
    .io_out  (_Multiplier_3_io_out)
  );
endmodule

module FixedComplexAdder(	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:7:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:7:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:7:7
  input  [15:0] io_in_a_0,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
                io_in_a_1,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
                io_in_b_0,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
                io_in_b_1,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
  output [15:0] io_out_0,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
                io_out_1	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
);

  Fixed16BitAdder_1 Adder_0 (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:13:33
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_a_0),
    .io_in_1 (io_in_b_0),
    .io_out  (io_out_0)
  );
  Fixed16BitAdder_1 Adder_1 (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:13:33
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_a_1),
    .io_in_1 (io_in_b_1),
    .io_out  (io_out_1)
  );
endmodule

module HadamardGate(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:12:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:12:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:12:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:12:14
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:12:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:12:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:12:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:12:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:12:14
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:12:14
);

  wire [15:0] _adder_io_out_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:15:27
  wire [15:0] _adder_io_out_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:15:27
  wire [15:0] _multiplier_1_io_out_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:14:39
  wire [15:0] _multiplier_1_io_out_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:14:39
  wire [15:0] _multiplier_0_io_out_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:14:39
  wire [15:0] _multiplier_0_io_out_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:14:39
  reg         delayed_r;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:45:30
  reg         delayed_r_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:45:30
  reg         delayed;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:45:30
  always @(posedge clock) begin	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
    delayed_r <= io_in_valid;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:45:30
    delayed_r_1 <= delayed_r;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:45:30
    delayed <= delayed_r_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:45:30
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
        delayed_r = _RANDOM[/*Zero width*/ 1'b0][0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7, :45:30
        delayed_r_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7, :45:30
        delayed = _RANDOM[/*Zero width*/ 1'b0][2];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7, :45:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FixedComplexMultiplier multiplier_0 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:14:39
    .clock     (clock),
    .reset     (reset),
    .io_in_a_0 (io_in_QSV_0_0),
    .io_in_a_1 (io_in_QSV_0_1),
    .io_out_0  (_multiplier_0_io_out_0),
    .io_out_1  (_multiplier_0_io_out_1)
  );
  FixedComplexMultiplier multiplier_1 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:14:39
    .clock     (clock),
    .reset     (reset),
    .io_in_a_0 (io_in_QSV_1_0),
    .io_in_a_1 (io_in_QSV_1_1),
    .io_out_0  (_multiplier_1_io_out_0),
    .io_out_1  (_multiplier_1_io_out_1)
  );
  FixedComplexAdder adder (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:15:27
    .clock     (clock),
    .reset     (reset),
    .io_in_a_0 (_multiplier_0_io_out_0),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:14:39
    .io_in_a_1 (_multiplier_0_io_out_1),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:14:39
    .io_in_b_0 (_multiplier_1_io_out_0),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:14:39
    .io_in_b_1 (_multiplier_1_io_out_1),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:14:39
    .io_out_0  (_adder_io_out_0),
    .io_out_1  (_adder_io_out_1)
  );
  assign io_out_QSV_0_0 = _adder_io_out_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7, :15:27
  assign io_out_QSV_0_1 = _adder_io_out_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7, :15:27
  assign io_out_QSV_1_0 = _adder_io_out_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7, :15:27
  assign io_out_QSV_1_1 = _adder_io_out_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7, :15:27
  assign io_out_valid = delayed;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:10:7, :45:30
endmodule

module ChooseGate(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
);

  HadamardGate gate (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:22:22
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_0_0),
    .io_in_QSV_0_1  (io_in_QSV_0_1),
    .io_in_QSV_1_0  (io_in_QSV_1_0),
    .io_in_QSV_1_1  (io_in_QSV_1_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (io_out_QSV_0_0),
    .io_out_QSV_0_1 (io_out_QSV_0_1),
    .io_out_QSV_1_0 (io_out_QSV_1_0),
    .io_out_QSV_1_1 (io_out_QSV_1_1),
    .io_out_valid   (io_out_valid)
  );
endmodule

module HGate2QubitVector16bit(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
);

  ChooseGate gate_0 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:44:53
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_0_0),
    .io_in_QSV_0_1  (io_in_QSV_0_1),
    .io_in_QSV_1_0  (io_in_QSV_1_0),
    .io_in_QSV_1_1  (io_in_QSV_1_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (io_out_QSV_0_0),
    .io_out_QSV_0_1 (io_out_QSV_0_1),
    .io_out_QSV_1_0 (io_out_QSV_1_0),
    .io_out_QSV_1_1 (io_out_QSV_1_1),
    .io_out_valid   (/* unused */)
  );
  ChooseGate gate_1 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:44:53
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_2_0),
    .io_in_QSV_0_1  (io_in_QSV_2_1),
    .io_in_QSV_1_0  (io_in_QSV_3_0),
    .io_in_QSV_1_1  (io_in_QSV_3_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (io_out_QSV_2_0),
    .io_out_QSV_0_1 (io_out_QSV_2_1),
    .io_out_QSV_1_0 (io_out_QSV_3_0),
    .io_out_QSV_1_1 (io_out_QSV_3_1),
    .io_out_valid   (io_out_valid)
  );
endmodule

module SwapGate(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_in_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_in_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_in_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_in_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_out_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_out_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_out_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
                io_out_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:219:15
);

  reg [15:0] reg_0_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
  reg [15:0] reg_0_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
  reg [15:0] reg_1_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
  reg [15:0] reg_1_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
  reg [15:0] reg_2_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
  reg [15:0] reg_2_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
  reg [15:0] reg_3_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
  reg [15:0] reg_3_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
  always @(posedge clock) begin	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
    if (reset) begin	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
      reg_0_0 <= io_in_QSV_0_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_0_1 <= io_in_QSV_0_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_1_0 <= io_in_QSV_1_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_1_1 <= io_in_QSV_1_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_2_0 <= io_in_QSV_2_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_2_1 <= io_in_QSV_2_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_3_0 <= io_in_QSV_3_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_3_1 <= io_in_QSV_3_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
    end
    else begin	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
      reg_0_0 <= io_in_QSV_0_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_0_1 <= io_in_QSV_0_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_1_0 <= io_in_QSV_1_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_1_1 <= io_in_QSV_1_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_2_0 <= io_in_QSV_2_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_2_1 <= io_in_QSV_2_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_3_0 <= io_in_QSV_3_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
      reg_3_1 <= io_in_QSV_3_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:226:22
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
      automatic logic [31:0] _RANDOM[0:3];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
        end	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
        reg_0_0 = _RANDOM[2'h0][15:0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
        reg_0_1 = _RANDOM[2'h0][31:16];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
        reg_1_0 = _RANDOM[2'h1][15:0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
        reg_1_1 = _RANDOM[2'h1][31:16];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
        reg_2_0 = _RANDOM[2'h2][15:0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
        reg_2_1 = _RANDOM[2'h2][31:16];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
        reg_3_0 = _RANDOM[2'h3][15:0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
        reg_3_1 = _RANDOM[2'h3][31:16];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_QSV_0_0 = reg_0_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
  assign io_out_QSV_0_1 = reg_0_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
  assign io_out_QSV_1_0 = reg_2_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
  assign io_out_QSV_1_1 = reg_2_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
  assign io_out_QSV_2_0 = reg_1_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
  assign io_out_QSV_2_1 = reg_1_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
  assign io_out_QSV_3_0 = reg_3_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
  assign io_out_QSV_3_1 = reg_3_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7, :226:22
  assign io_out_valid = io_in_valid;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:218:7
endmodule

module ChooseGate_2(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
);

  SwapGate gate (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:30:22
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_0_0),
    .io_in_QSV_0_1  (io_in_QSV_0_1),
    .io_in_QSV_1_0  (io_in_QSV_1_0),
    .io_in_QSV_1_1  (io_in_QSV_1_1),
    .io_in_QSV_2_0  (io_in_QSV_2_0),
    .io_in_QSV_2_1  (io_in_QSV_2_1),
    .io_in_QSV_3_0  (io_in_QSV_3_0),
    .io_in_QSV_3_1  (io_in_QSV_3_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (io_out_QSV_0_0),
    .io_out_QSV_0_1 (io_out_QSV_0_1),
    .io_out_QSV_1_0 (io_out_QSV_1_0),
    .io_out_QSV_1_1 (io_out_QSV_1_1),
    .io_out_QSV_2_0 (io_out_QSV_2_0),
    .io_out_QSV_2_1 (io_out_QSV_2_1),
    .io_out_QSV_3_0 (io_out_QSV_3_0),
    .io_out_QSV_3_1 (io_out_QSV_3_1),
    .io_out_valid   (io_out_valid)
  );
endmodule

module SWGate2QubitVector16bit(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
);

  ChooseGate_2 gate_0 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:44:53
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_0_0),
    .io_in_QSV_0_1  (io_in_QSV_0_1),
    .io_in_QSV_1_0  (io_in_QSV_1_0),
    .io_in_QSV_1_1  (io_in_QSV_1_1),
    .io_in_QSV_2_0  (io_in_QSV_2_0),
    .io_in_QSV_2_1  (io_in_QSV_2_1),
    .io_in_QSV_3_0  (io_in_QSV_3_0),
    .io_in_QSV_3_1  (io_in_QSV_3_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (io_out_QSV_0_0),
    .io_out_QSV_0_1 (io_out_QSV_0_1),
    .io_out_QSV_1_0 (io_out_QSV_1_0),
    .io_out_QSV_1_1 (io_out_QSV_1_1),
    .io_out_QSV_2_0 (io_out_QSV_2_0),
    .io_out_QSV_2_1 (io_out_QSV_2_1),
    .io_out_QSV_3_0 (io_out_QSV_3_0),
    .io_out_QSV_3_1 (io_out_QSV_3_1),
    .io_out_valid   (io_out_valid)
  );
endmodule

module GeneratePiplinedGates(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:18:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:18:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:18:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_in_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_in_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_in_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_in_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_out_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_out_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_out_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
                io_out_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:20:14
);

  wire [15:0] _m_io_out_QSV_0_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
  wire [15:0] _m_io_out_QSV_0_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
  wire [15:0] _m_io_out_QSV_1_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
  wire [15:0] _m_io_out_QSV_1_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
  wire [15:0] _m_io_out_QSV_2_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
  wire [15:0] _m_io_out_QSV_2_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
  wire [15:0] _m_io_out_QSV_3_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
  wire [15:0] _m_io_out_QSV_3_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
  wire        _m_io_out_valid;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
  HGate2QubitVector16bit m (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_0_0),
    .io_in_QSV_0_1  (io_in_QSV_0_1),
    .io_in_QSV_1_0  (io_in_QSV_1_0),
    .io_in_QSV_1_1  (io_in_QSV_1_1),
    .io_in_QSV_2_0  (io_in_QSV_2_0),
    .io_in_QSV_2_1  (io_in_QSV_2_1),
    .io_in_QSV_3_0  (io_in_QSV_3_0),
    .io_in_QSV_3_1  (io_in_QSV_3_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (_m_io_out_QSV_0_0),
    .io_out_QSV_0_1 (_m_io_out_QSV_0_1),
    .io_out_QSV_1_0 (_m_io_out_QSV_1_0),
    .io_out_QSV_1_1 (_m_io_out_QSV_1_1),
    .io_out_QSV_2_0 (_m_io_out_QSV_2_0),
    .io_out_QSV_2_1 (_m_io_out_QSV_2_1),
    .io_out_QSV_3_0 (_m_io_out_QSV_3_0),
    .io_out_QSV_3_1 (_m_io_out_QSV_3_1),
    .io_out_valid   (_m_io_out_valid)
  );
  SWGate2QubitVector16bit m_1 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (_m_io_out_QSV_0_0),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
    .io_in_QSV_0_1  (_m_io_out_QSV_0_1),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
    .io_in_QSV_1_0  (_m_io_out_QSV_1_0),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
    .io_in_QSV_1_1  (_m_io_out_QSV_1_1),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
    .io_in_QSV_2_0  (_m_io_out_QSV_2_0),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
    .io_in_QSV_2_1  (_m_io_out_QSV_2_1),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
    .io_in_QSV_3_0  (_m_io_out_QSV_3_0),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
    .io_in_QSV_3_1  (_m_io_out_QSV_3_1),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
    .io_in_valid    (_m_io_out_valid),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:33:23
    .io_out_QSV_0_0 (io_out_QSV_0_0),
    .io_out_QSV_0_1 (io_out_QSV_0_1),
    .io_out_QSV_1_0 (io_out_QSV_1_0),
    .io_out_QSV_1_1 (io_out_QSV_1_1),
    .io_out_QSV_2_0 (io_out_QSV_2_0),
    .io_out_QSV_2_1 (io_out_QSV_2_1),
    .io_out_QSV_3_0 (io_out_QSV_3_0),
    .io_out_QSV_3_1 (io_out_QSV_3_1),
    .io_out_valid   (io_out_valid)
  );
endmodule

