// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Fixed16BitMultiplier(	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
  input  [15:0] io_in_0,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:24:14
                io_in_1,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:24:14
  output [15:0] io_out	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:24:14
);

  reg [15:0] outreg;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:36:23
  always @(posedge clock) begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    if (reset)	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      outreg <= 16'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:36:23
    else begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      automatic logic [29:0] _wireout_T =
        {{14{io_in_0[15]}}, io_in_0} * {{14{io_in_1[15]}}, io_in_1};	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:32:24, :33:24, :34:20
      outreg <= _wireout_T[29:14];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:34:20, :36:23, :37:20
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
        outreg = _RANDOM[/*Zero width*/ 1'b0][15:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7, :36:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out = outreg;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7, :36:23
endmodule

module Fixed16BitAdder(	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
  input  [15:0] io_in_0,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:9:14
                io_in_1,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:9:14
  output [15:0] io_out	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:9:14
);

  reg [15:0] reg_0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:14:22
  always @(posedge clock) begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    if (reset)	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      reg_0 <= 16'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:14:22
    else	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      reg_0 <= io_in_0 + io_in_1;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:14:22, :15:25
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
        reg_0 = _RANDOM[/*Zero width*/ 1'b0][15:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7, :14:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out = reg_0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7, :14:22
endmodule

module CollapseProbability(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
  input         clock,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
                reset,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:71:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:71:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:71:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:71:14
  input         io_in_valid,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:71:14
  output        io_out_valid,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:71:14
  output [15:0] io_out_Measured_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:71:14
                io_out_Measured_1	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:71:14
);

  wire [15:0] _square_3_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
  wire [15:0] _square_2_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
  wire [15:0] _square_1_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
  wire [15:0] _square_0_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
  reg         io_out_valid_r;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:135:32
  reg         io_out_valid_r_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:135:32
  reg         io_out_valid_r_2;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:135:32
  always @(posedge clock) begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
    io_out_valid_r <= io_in_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:135:32
    io_out_valid_r_1 <= io_out_valid_r;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:135:32
    io_out_valid_r_2 <= io_out_valid_r_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:135:32
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
        io_out_valid_r = _RANDOM[/*Zero width*/ 1'b0][0];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7, :135:32
        io_out_valid_r_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7, :135:32
        io_out_valid_r_2 = _RANDOM[/*Zero width*/ 1'b0][2];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7, :135:32
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Fixed16BitMultiplier square_0 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_QSV_0_0),
    .io_in_1 (io_in_QSV_0_0),
    .io_out  (_square_0_io_out)
  );
  Fixed16BitMultiplier square_1 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_QSV_0_1),
    .io_in_1 (io_in_QSV_0_1),
    .io_out  (_square_1_io_out)
  );
  Fixed16BitMultiplier square_2 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_QSV_1_0),
    .io_in_1 (io_in_QSV_1_0),
    .io_out  (_square_2_io_out)
  );
  Fixed16BitMultiplier square_3 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_QSV_1_1),
    .io_in_1 (io_in_QSV_1_1),
    .io_out  (_square_3_io_out)
  );
  Fixed16BitAdder addlayer_0 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:79:62
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (_square_0_io_out),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
    .io_in_1 (_square_1_io_out),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
    .io_out  (io_out_Measured_0)
  );
  Fixed16BitAdder addlayer_1 (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:79:62
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (_square_2_io_out),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
    .io_in_1 (_square_3_io_out),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:78:64
    .io_out  (io_out_Measured_1)
  );
  assign io_out_valid = io_out_valid_r_2;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:70:7, :135:32
endmodule

module LinearCongruentialGenerator(	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
  input         clock,	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
                reset,	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
  input  [31:0] io_in_seed,	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:21:14
  input         io_in_feed,	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:21:14
                io_in_next,	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:21:14
  output [31:0] io_out_Value	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:21:14
);

  reg [31:0] value;	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:28:23
  always @(posedge clock) begin	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
    if (reset)	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
      value <= 32'h0;	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:28:23
    else if (io_in_feed)	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:21:14
      value <= io_in_seed;	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:28:23
    else if (io_in_next) begin	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:21:14
      automatic logic [34:0] _value_T_3;	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:34:34
      _value_T_3 = ({3'h0, value} * 35'h5 + 35'h1) % 35'h20;	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:28:23, :34:{21,27,34}
      value <= {26'h0, _value_T_3[5:0]};	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:28:23, :34:{11,34}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
        value = _RANDOM[/*Zero width*/ 1'b0];	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7, :28:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_Value = value;	// \\src\\main\\scala\\QuantumStateUnit\\OtherComponents\\PsuedoRandomGenerator\\RandomNumberGenerator.scala:20:7, :28:23
endmodule

module CompareWithRandom(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
  input         clock,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
                reset,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
  input  [15:0] io_in_probability,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:12:14
  input  [31:0] io_in_seed,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:12:14
  input         io_in_en,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:12:14
                io_in_valid,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:12:14
  output        io_out_valid,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:12:14
                io_out_value	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:12:14
);

  wire [31:0] _RNG_io_out_Value;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:28:27
  reg         prev;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:26:28
  reg  [15:0] RNGnumber;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:42:28
  reg         determinedValue;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:50:32
  reg         io_out_valid_r;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:52:32
  always @(posedge clock) begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
    if (reset) begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
      prev <= 1'h0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7, :26:28
      RNGnumber <= 16'h0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:42:28
      determinedValue <= 1'h0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7, :50:32
    end
    else begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
      prev <= io_in_en;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:26:28
      RNGnumber <= {_RNG_io_out_Value[6:0], 9'h0};	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:28:27, :42:28, :46:{34,41}
      determinedValue <=
        RNGnumber > io_in_probability & io_in_en & io_in_valid
        | ~(RNGnumber < io_in_probability & io_in_en & io_in_valid) & determinedValue;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:42:28, :50:32, :55:{21,61,76}, :56:23, :59:{21,61,76}, :60:23
    end
    io_out_valid_r <= io_in_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:52:32
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
        prev = _RANDOM[/*Zero width*/ 1'b0][0];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7, :26:28
        RNGnumber = _RANDOM[/*Zero width*/ 1'b0][16:1];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7, :26:28, :42:28
        determinedValue = _RANDOM[/*Zero width*/ 1'b0][17];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7, :26:28, :50:32
        io_out_valid_r = _RANDOM[/*Zero width*/ 1'b0][18];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7, :26:28, :52:32
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  LinearCongruentialGenerator RNG (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:28:27
    .clock        (clock),
    .reset        (reset),
    .io_in_seed   (io_in_seed),
    .io_in_feed   (io_in_en & ~prev),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:26:28, :30:{30,33}
    .io_in_next   (io_in_en),
    .io_out_Value (_RNG_io_out_Value)
  );
  assign io_out_valid = io_out_valid_r;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7, :52:32
  assign io_out_value = determinedValue;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:11:7, :50:32
endmodule

module QGPMuxLayer(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:188:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
  input         io_in_sel,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
  output [15:0] io_out_QSV_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
                io_out_QSV_1	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:189:14
);

  assign io_out_QSV_0 = io_in_sel ? 16'h0 : io_in_QSV_0_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:188:7, :189:14, :195:15
  assign io_out_QSV_1 = io_in_sel ? io_in_QSV_1_1 : 16'h0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\AcceleratedGatePool.scala:188:7, :189:14, :195:15
endmodule

module NewQSV(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:183:8
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:184:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:184:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:184:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:184:14
  input         io_in_sel,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:184:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:184:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:184:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:184:14
                io_out_QSV_1_1	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:184:14
);

  QGPMuxLayer reallayerofMux (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:189:30
    .io_in_QSV_0_0 (io_in_QSV_0_0),
    .io_in_QSV_1_1 (io_in_QSV_1_0),
    .io_in_sel     (io_in_sel),
    .io_out_QSV_0  (io_out_QSV_0_0),
    .io_out_QSV_1  (io_out_QSV_1_0)
  );
  QGPMuxLayer imaglayerofMux (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:190:30
    .io_in_QSV_0_0 (io_in_QSV_0_1),
    .io_in_QSV_1_1 (io_in_QSV_1_1),
    .io_in_sel     (io_in_sel),
    .io_out_QSV_0  (io_out_QSV_0_1),
    .io_out_QSV_1  (io_out_QSV_1_1)
  );
endmodule

module Fixed16BitDivider(	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
  input  [15:0] io_in_den,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:43:14
  output [15:0] io_out	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:43:14
);

  reg [15:0] outreg;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:56:23
  always @(posedge clock) begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
    if (reset)	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
      outreg <= 16'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:49:27, :56:23
    else	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
      outreg <= {io_in_den[1:0], 14'h0};	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:54:11, :56:23, :57:20
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
        outreg = _RANDOM[/*Zero width*/ 1'b0][15:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7, :56:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out = outreg;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:41:7, :56:23
endmodule

module Fixed16SquareRoot(	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
  input  [15:0] io_in,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:89:14
  input         io_in_valid,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:89:14
  output        io_out_valid,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:89:14
  output [15:0] io_out	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:89:14
);

  wire [15:0] _multiplier_io_out;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:120:29
  reg  [15:0] currentValue;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:113:30
  reg         validReg;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:115:30
  reg  [15:0] multiplierReg;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:121:30
  always @(posedge clock) begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
    if (reset) begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
      currentValue <= 16'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:113:30
      validReg <= 1'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7, :115:30
      multiplierReg <= 16'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:113:30, :121:30
    end
    else begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
      automatic logic _GEN;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:126:22
      _GEN = $signed(multiplierReg) < $signed(io_in);	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:121:30, :126:22
      if ($signed(_multiplier_io_out) > $signed(io_in + 16'h1))	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:120:29, :127:35, :141:{26,34}
        currentValue <= currentValue - 16'h1;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:113:30, :142:34
      else if (io_in_valid) begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:89:14
        if (_GEN)	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:126:22
          currentValue <= currentValue + 16'h1;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:113:30, :127:35
      end
      else	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:89:14
        currentValue <= 16'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:113:30
      validReg <=
        io_in_valid
        & ($signed(multiplierReg) <= $signed(io_in) & io_in_valid | ~_GEN & validReg);	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:115:30, :121:30, :126:{22,30}, :128:19, :131:{23,33,47}, :132:14, :136:21, :138:18
      multiplierReg <= _multiplier_io_out;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:120:29, :121:30
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
      automatic logic [31:0] _RANDOM[0:1];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
        end	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
        currentValue = _RANDOM[1'h0][15:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7, :113:30
        validReg = _RANDOM[1'h1][0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7, :115:30
        multiplierReg = _RANDOM[1'h1][16:1];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7, :115:30, :121:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Fixed16BitMultiplier multiplier (	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:120:29
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (currentValue),	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:113:30
    .io_in_1 (currentValue),	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:113:30
    .io_out  (_multiplier_io_out)
  );
  assign io_out_valid = validReg;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7, :115:30
  assign io_out = currentValue;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:87:7, :113:30
endmodule

module GetNormalization(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
  input         clock,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
                reset,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
  input  [15:0] io_in_probability_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:144:14
                io_in_probability_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:144:14
  input         io_in_en,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:144:14
                io_in_valid,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:144:14
  output        io_out_valid,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:144:14
  output [15:0] io_out_Normalize	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:144:14
);

  wire [15:0] _sqrt_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:159:27
  wire [15:0] _reciprocol_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:158:27
  wire [15:0] _addtogether_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:157:27
  reg         addValidReg;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:163:28
  reg         divValidReg;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:168:28
  reg  [15:0] RegNormalizeOut;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:175:32
  always @(posedge clock) begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
    if (reset) begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
      addValidReg <= 1'h0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7, :163:28
      divValidReg <= 1'h0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7, :168:28
      RegNormalizeOut <= 16'h0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:175:32
    end
    else begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
      addValidReg <= io_in_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:163:28
      divValidReg <= addValidReg;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:163:28, :168:28
      if (io_in_en)	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:144:14
        RegNormalizeOut <= _sqrt_io_out;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:159:27, :175:32
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
        addValidReg = _RANDOM[/*Zero width*/ 1'b0][0];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7, :163:28
        divValidReg = _RANDOM[/*Zero width*/ 1'b0][1];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7, :163:28, :168:28
        RegNormalizeOut = _RANDOM[/*Zero width*/ 1'b0][17:2];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7, :163:28, :175:32
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Fixed16BitAdder addtogether (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:157:27
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_probability_0),
    .io_in_1 (io_in_probability_1),
    .io_out  (_addtogether_io_out)
  );
  Fixed16BitDivider reciprocol (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:158:27
    .clock     (clock),
    .reset     (reset),
    .io_in_den (_addtogether_io_out),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:157:27
    .io_out    (_reciprocol_io_out)
  );
  Fixed16SquareRoot sqrt (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:159:27
    .clock        (clock),
    .reset        (reset),
    .io_in        (_reciprocol_io_out),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:158:27
    .io_in_valid  (divValidReg),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:168:28
    .io_out_valid (io_out_valid),
    .io_out       (_sqrt_io_out)
  );
  assign io_out_Normalize = RegNormalizeOut;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\Components\\Components.scala:143:7, :175:32
endmodule

module MeasurementGate(	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
  input         clock,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
                reset,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
  input  [31:0] io_in_noise,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
  input         io_in_sendNorm,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
                io_in_valid,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
  output        io_out_valid,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
                io_out_Normalize,	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
  output        io_out_measured	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:11:14
);

  wire        _normalizeNumber_io_out_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:26:31
  wire [15:0] _normalizeNumber_io_out_Normalize;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:26:31
  wire [15:0] _QSVout_io_out_QSV_0_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:25:31
  wire [15:0] _QSVout_io_out_QSV_0_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:25:31
  wire [15:0] _QSVout_io_out_QSV_1_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:25:31
  wire [15:0] _QSVout_io_out_QSV_1_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:25:31
  wire        _numberGenerator_io_out_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:24:31
  wire        _numberGenerator_io_out_value;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:24:31
  wire        _findProbability_io_out_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:23:31
  wire [15:0] _findProbability_io_out_Measured_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:23:31
  wire [15:0] _findProbability_io_out_Measured_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:23:31
  reg         normalize;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:32:26
  reg         collapsevalid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:33:30
  reg         r;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:37:55
  wire        collapseNumberSel = _numberGenerator_io_out_valid & ~io_in_sendNorm;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:24:31, :48:{56,58}
  reg         findProbability_io_in_valid_r;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:50:76
  always @(posedge clock) begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
    if (reset) begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
      normalize <= 1'h0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :32:26
      collapsevalid <= 1'h0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :33:30
    end
    else begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
      normalize <=
        io_in_valid & (_numberGenerator_io_out_valid | io_in_sendNorm | normalize);	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:24:31, :32:26, :34:56, :35:15, :40:22, :41:19
      collapsevalid <=
        io_in_valid
        & (~_findProbability_io_out_valid & r | io_in_sendNorm | collapsevalid);	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:23:31, :33:30, :37:{9,39,55,108}, :38:19, :40:22, :42:19
    end
    r <= _findProbability_io_out_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:23:31, :37:55
    findProbability_io_in_valid_r <= normalize;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:32:26, :50:76
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
        normalize = _RANDOM[/*Zero width*/ 1'b0][0];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :32:26
        collapsevalid = _RANDOM[/*Zero width*/ 1'b0][1];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :32:26, :33:30
        r = _RANDOM[/*Zero width*/ 1'b0][2];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :32:26, :37:55
        findProbability_io_in_valid_r = _RANDOM[/*Zero width*/ 1'b0][3];	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :32:26, :50:76
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CollapseProbability findProbability (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:23:31
    .clock             (clock),
    .reset             (reset),
    .io_in_QSV_0_0     (collapseNumberSel ? _QSVout_io_out_QSV_0_0 : io_in_QSV_0_0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:25:31, :48:56, :49:43
    .io_in_QSV_0_1     (collapseNumberSel ? _QSVout_io_out_QSV_0_1 : io_in_QSV_0_1),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:25:31, :48:56, :49:43
    .io_in_QSV_1_0     (collapseNumberSel ? _QSVout_io_out_QSV_1_0 : io_in_QSV_1_0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:25:31, :48:56, :49:43
    .io_in_QSV_1_1     (collapseNumberSel ? _QSVout_io_out_QSV_1_1 : io_in_QSV_1_1),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:25:31, :48:56, :49:43
    .io_in_valid       (collapseNumberSel ? findProbability_io_in_valid_r : io_in_valid),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:48:56, :50:{43,76}
    .io_out_valid      (_findProbability_io_out_valid),
    .io_out_Measured_0 (_findProbability_io_out_Measured_0),
    .io_out_Measured_1 (_findProbability_io_out_Measured_1)
  );
  CompareWithRandom numberGenerator (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:24:31
    .clock             (clock),
    .reset             (reset),
    .io_in_probability (_findProbability_io_out_Measured_0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:23:31
    .io_in_seed        (io_in_noise),
    .io_in_en          (normalize),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:32:26
    .io_in_valid       (_findProbability_io_out_valid | normalize),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:23:31, :32:26, :56:69
    .io_out_valid      (_numberGenerator_io_out_valid),
    .io_out_value      (_numberGenerator_io_out_value)
  );
  NewQSV QSVout (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:25:31
    .io_in_QSV_0_0  (io_in_QSV_0_0),
    .io_in_QSV_0_1  (io_in_QSV_0_1),
    .io_in_QSV_1_0  (io_in_QSV_1_0),
    .io_in_QSV_1_1  (io_in_QSV_1_1),
    .io_in_sel      (_numberGenerator_io_out_value),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:24:31
    .io_out_QSV_0_0 (_QSVout_io_out_QSV_0_0),
    .io_out_QSV_0_1 (_QSVout_io_out_QSV_0_1),
    .io_out_QSV_1_0 (_QSVout_io_out_QSV_1_0),
    .io_out_QSV_1_1 (_QSVout_io_out_QSV_1_1)
  );
  GetNormalization normalizeNumber (	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:26:31
    .clock               (clock),
    .reset               (reset),
    .io_in_probability_0 (_findProbability_io_out_Measured_0),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:23:31
    .io_in_probability_1 (_findProbability_io_out_Measured_1),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:23:31
    .io_in_en            (~(normalize & _normalizeNumber_io_out_valid)),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:26:31, :32:26, :45:{31,43}
    .io_in_valid         (collapsevalid & _findProbability_io_out_valid),	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:23:31, :33:30, :64:56
    .io_out_valid        (_normalizeNumber_io_out_valid),
    .io_out_Normalize    (_normalizeNumber_io_out_Normalize)
  );
  assign io_out_valid = _normalizeNumber_io_out_valid;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :26:31
  assign io_out_QSV_0_0 = _QSVout_io_out_QSV_0_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :25:31
  assign io_out_QSV_0_1 = _QSVout_io_out_QSV_0_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :25:31
  assign io_out_QSV_1_0 = _QSVout_io_out_QSV_1_0;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :25:31
  assign io_out_QSV_1_1 = _QSVout_io_out_QSV_1_1;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :25:31
  assign io_out_Normalize = normalize ? _normalizeNumber_io_out_Normalize : 16'h4000;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :26:31, :29:48, :32:26, :71:43
  assign io_out_measured = _numberGenerator_io_out_value;	// \\src\\main\\scala\\QuantumStateUnit\\GateArchitecture\\FixedPointGatePool\\MeasurementGate\\FixedPointMeasurementGate.scala:9:7, :24:31
endmodule

