// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SplitMultiplier(	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
  input  [15:0] io_a,	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:100:14
  output [15:0] io_out_fixed,	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:100:14
  input         io_valid_in,	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:100:14
  output        io_valid_out	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:100:14
);

  reg [31:0] partials_0;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:126:25
  reg [31:0] partials_1;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:126:25
  reg [31:0] partials_2;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:126:25
  reg [31:0] partials_3;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:126:25
  reg [31:0] acc;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:127:25
  reg        valid;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:128:25
  reg [31:0] REG_0;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:144:23
  reg [31:0] REG_1;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:144:23
  reg [31:0] REG_2;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:144:23
  reg [31:0] REG_1_0;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:147:18
  reg        REG_2_0;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:150:20
  reg [31:0] REG_3_0;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:144:23
  reg [31:0] REG_3_1;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:144:23
  reg [31:0] REG_4;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:147:18
  reg        REG_5;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:150:20
  reg [31:0] REG_6_0;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:144:23
  reg [31:0] REG_7;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:147:18
  reg        REG_8;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:150:20
  always @(posedge clock) begin	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
    partials_0 <= {16'h0, io_a};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:120:24, :126:25
    partials_1 <= {10'h0, io_a, 6'h0};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:120:{24,44}, :126:25
    partials_2 <= {4'h0, {4'h0, io_a} * 20'hD, 8'h0};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :120:{24,34}, :126:25
    partials_3 <= {3'h0, io_a, 13'h0};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:120:{34,44}, :126:25
    acc <= partials_0;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:126:25, :127:25
    valid <= io_valid_in;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:128:25
    REG_0 <= partials_1;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:126:25, :144:23
    REG_1 <= partials_2;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:126:25, :144:23
    REG_2 <= partials_3;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:126:25, :144:23
    REG_1_0 <= acc + REG_0;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:127:25, :144:23, :147:{18,23}
    REG_2_0 <= valid;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:128:25, :150:20
    REG_3_0 <= REG_1;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:144:23
    REG_3_1 <= REG_2;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:144:23
    REG_4 <= REG_1_0 + REG_3_0;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:144:23, :147:{18,23}
    REG_5 <= REG_2_0;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:150:20
    REG_6_0 <= REG_3_1;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:144:23
    REG_7 <= REG_4 + REG_6_0;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:144:23, :147:{18,23}
    REG_8 <= REG_5;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:150:20
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
      automatic logic [31:0] _RANDOM[0:14];	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
        for (logic [3:0] i = 4'h0; i < 4'hF; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
        end	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
        partials_0 = _RANDOM[4'h0];	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :126:25
        partials_1 = _RANDOM[4'h1];	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :126:25
        partials_2 = _RANDOM[4'h2];	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :126:25
        partials_3 = _RANDOM[4'h3];	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :126:25
        acc = _RANDOM[4'h4];	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :127:25
        valid = _RANDOM[4'h5][0];	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :128:25
        REG_0 = {_RANDOM[4'h5][31:1], _RANDOM[4'h6][0]};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :128:25, :144:23
        REG_1 = {_RANDOM[4'h6][31:1], _RANDOM[4'h7][0]};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :144:23
        REG_2 = {_RANDOM[4'h7][31:1], _RANDOM[4'h8][0]};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :144:23
        REG_1_0 = {_RANDOM[4'h8][31:1], _RANDOM[4'h9][0]};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :144:23, :147:18
        REG_2_0 = _RANDOM[4'h9][1];	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :147:18, :150:20
        REG_3_0 = {_RANDOM[4'h9][31:2], _RANDOM[4'hA][1:0]};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :144:23, :147:18
        REG_3_1 = {_RANDOM[4'hA][31:2], _RANDOM[4'hB][1:0]};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :144:23
        REG_4 = {_RANDOM[4'hB][31:2], _RANDOM[4'hC][1:0]};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :144:23, :147:18
        REG_5 = _RANDOM[4'hC][2];	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :147:18, :150:20
        REG_6_0 = {_RANDOM[4'hC][31:3], _RANDOM[4'hD][2:0]};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :144:23, :147:18
        REG_7 = {_RANDOM[4'hD][31:3], _RANDOM[4'hE][2:0]};	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :144:23, :147:18
        REG_8 = _RANDOM[4'hE][3];	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :147:18, :150:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_fixed = REG_7[29:14];	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :147:18, :157:22
  assign io_valid_out = REG_8;	// \\src\\main\\scala\\FixedPointUnit\\AdvancedFixedPoint.scala:97:7, :150:20
endmodule

module Fixed16BitAdder(	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
  input  [15:0] io_in_0,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:9:14
                io_in_1,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:9:14
  output [15:0] io_out	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:9:14
);

  reg [15:0] reg_0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:14:22
  always @(posedge clock) begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    if (reset)	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      reg_0 <= 16'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:14:22
    else	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      reg_0 <= io_in_0 + io_in_1;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:14:22, :15:25
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
        reg_0 = _RANDOM[/*Zero width*/ 1'b0][15:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7, :14:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out = reg_0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:7:7, :14:22
endmodule

module FixedComplexAdder(	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:7:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:7:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:7:7
  input  [15:0] io_in_a_0,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
                io_in_a_1,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
                io_in_b_0,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
                io_in_b_1,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
  output [15:0] io_out_0,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
                io_out_1	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:8:14
);

  Fixed16BitAdder Adder_0 (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:13:33
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_a_0),
    .io_in_1 (io_in_b_0),
    .io_out  (io_out_0)
  );
  Fixed16BitAdder Adder_1 (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:13:33
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_a_1),
    .io_in_1 (io_in_b_1),
    .io_out  (io_out_1)
  );
endmodule

module Fixed16BitAdder_2(	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
  input  [15:0] io_in_0,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:24:14
                io_in_1,	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:24:14
  output [15:0] io_out	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:24:14
);

  reg [15:0] reg_0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:29:22
  always @(posedge clock) begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    if (reset)	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      reg_0 <= 16'h0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:29:22
    else	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      reg_0 <= io_in_0 - io_in_1;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:29:22, :30:25
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
        reg_0 = _RANDOM[/*Zero width*/ 1'b0][15:0];	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7, :29:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out = reg_0;	// \\src\\main\\scala\\FixedPointUnit\\FixedPointUnit.scala:22:7, :29:22
endmodule

module FixedComplexSubber(	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:26:7
  input         clock,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:26:7
                reset,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:26:7
  input  [15:0] io_in_a_0,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:27:14
                io_in_a_1,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:27:14
                io_in_b_0,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:27:14
                io_in_b_1,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:27:14
  output [15:0] io_out_0,	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:27:14
                io_out_1	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:27:14
);

  Fixed16BitAdder_2 Subber_0 (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:32:34
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_a_0),
    .io_in_1 (io_in_b_0),
    .io_out  (io_out_0)
  );
  Fixed16BitAdder_2 Subber_1 (	// \\src\\main\\scala\\FixedPointUnit\\ComplexFixedPoint\\FixedComplexUnit.scala:32:34
    .clock   (clock),
    .reset   (reset),
    .io_in_0 (io_in_a_1),
    .io_in_1 (io_in_b_1),
    .io_out  (io_out_1)
  );
endmodule

module HadamardGate(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:75:15
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:75:15
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:75:15
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:75:15
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:75:15
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:75:15
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:75:15
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:75:15
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:75:15
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:75:15
);

  wire [15:0] _multiplier_3_io_out_fixed;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
  wire        _multiplier_3_io_valid_out;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
  wire [15:0] _multiplier_2_io_out_fixed;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
  wire        _multiplier_2_io_valid_out;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
  wire [15:0] _multiplier_1_io_out_fixed;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
  wire        _multiplier_1_io_valid_out;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
  wire [15:0] _multiplier_0_io_out_fixed;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
  wire        _multiplier_0_io_valid_out;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
  reg         delay;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:120:28
  always @(posedge clock)	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
    delay <=
      _multiplier_0_io_valid_out & _multiplier_1_io_valid_out & _multiplier_2_io_valid_out
      & _multiplier_3_io_valid_out;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38, :120:28, :123:34
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
        delay = _RANDOM[/*Zero width*/ 1'b0][0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7, :120:28
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SplitMultiplier multiplier_0 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .clock        (clock),
    .io_a         (io_in_QSV_0_0),
    .io_out_fixed (_multiplier_0_io_out_fixed),
    .io_valid_in  (io_in_valid),
    .io_valid_out (_multiplier_0_io_valid_out)
  );
  SplitMultiplier multiplier_1 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .clock        (clock),
    .io_a         (io_in_QSV_0_1),
    .io_out_fixed (_multiplier_1_io_out_fixed),
    .io_valid_in  (io_in_valid),
    .io_valid_out (_multiplier_1_io_valid_out)
  );
  SplitMultiplier multiplier_2 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .clock        (clock),
    .io_a         (io_in_QSV_1_0),
    .io_out_fixed (_multiplier_2_io_out_fixed),
    .io_valid_in  (io_in_valid),
    .io_valid_out (_multiplier_2_io_valid_out)
  );
  SplitMultiplier multiplier_3 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .clock        (clock),
    .io_a         (io_in_QSV_1_1),
    .io_out_fixed (_multiplier_3_io_out_fixed),
    .io_valid_in  (io_in_valid),
    .io_valid_out (_multiplier_3_io_valid_out)
  );
  FixedComplexAdder adder (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:80:21
    .clock     (clock),
    .reset     (reset),
    .io_in_a_0 (_multiplier_0_io_out_fixed),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .io_in_a_1 (_multiplier_1_io_out_fixed),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .io_in_b_0 (_multiplier_2_io_out_fixed),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .io_in_b_1 (_multiplier_3_io_out_fixed),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .io_out_0  (io_out_QSV_0_0),
    .io_out_1  (io_out_QSV_0_1)
  );
  FixedComplexSubber subber (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:81:22
    .clock     (clock),
    .reset     (reset),
    .io_in_a_0 (_multiplier_0_io_out_fixed),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .io_in_a_1 (_multiplier_1_io_out_fixed),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .io_in_b_0 (_multiplier_2_io_out_fixed),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .io_in_b_1 (_multiplier_3_io_out_fixed),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:79:38
    .io_out_0  (io_out_QSV_1_0),
    .io_out_1  (io_out_QSV_1_1)
  );
  assign io_out_valid = delay;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:72:7, :120:28
endmodule

module ChooseGate(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
);

  HadamardGate gate (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:22:22
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_0_0),
    .io_in_QSV_0_1  (io_in_QSV_0_1),
    .io_in_QSV_1_0  (io_in_QSV_1_0),
    .io_in_QSV_1_1  (io_in_QSV_1_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (io_out_QSV_0_0),
    .io_out_QSV_0_1 (io_out_QSV_0_1),
    .io_out_QSV_1_0 (io_out_QSV_1_0),
    .io_out_QSV_1_1 (io_out_QSV_1_1),
    .io_out_valid   (io_out_valid)
  );
endmodule

module HGate2QubitVector16bit(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
);

  wire _gate_1_io_out_valid;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:44:53
  wire _gate_0_io_out_valid;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:44:53
  ChooseGate gate_0 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:44:53
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_0_0),
    .io_in_QSV_0_1  (io_in_QSV_0_1),
    .io_in_QSV_1_0  (io_in_QSV_1_0),
    .io_in_QSV_1_1  (io_in_QSV_1_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (io_out_QSV_0_0),
    .io_out_QSV_0_1 (io_out_QSV_0_1),
    .io_out_QSV_1_0 (io_out_QSV_1_0),
    .io_out_QSV_1_1 (io_out_QSV_1_1),
    .io_out_valid   (_gate_0_io_out_valid)
  );
  ChooseGate gate_1 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:44:53
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_2_0),
    .io_in_QSV_0_1  (io_in_QSV_2_1),
    .io_in_QSV_1_0  (io_in_QSV_3_0),
    .io_in_QSV_1_1  (io_in_QSV_3_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (io_out_QSV_2_0),
    .io_out_QSV_0_1 (io_out_QSV_2_1),
    .io_out_QSV_1_0 (io_out_QSV_3_0),
    .io_out_QSV_1_1 (io_out_QSV_3_1),
    .io_out_valid   (_gate_1_io_out_valid)
  );
  assign io_out_valid = _gate_0_io_out_valid & _gate_1_io_out_valid;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7, :44:53, :48:52
endmodule

module SwapGate(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_in_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_in_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_in_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_in_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_out_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_out_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_out_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
                io_out_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:319:15
);

  reg [15:0] reg_0_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
  reg [15:0] reg_0_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
  reg [15:0] reg_1_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
  reg [15:0] reg_1_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
  reg [15:0] reg_2_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
  reg [15:0] reg_2_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
  reg [15:0] reg_3_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
  reg [15:0] reg_3_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
  reg        delay;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:327:22
  always @(posedge clock) begin	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
    if (reset) begin	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
      reg_0_0 <= io_in_QSV_0_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_0_1 <= io_in_QSV_0_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_1_0 <= io_in_QSV_1_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_1_1 <= io_in_QSV_1_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_2_0 <= io_in_QSV_2_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_2_1 <= io_in_QSV_2_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_3_0 <= io_in_QSV_3_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_3_1 <= io_in_QSV_3_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      delay <= io_in_valid;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:327:22
    end
    else begin	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
      reg_0_0 <= io_in_QSV_0_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_0_1 <= io_in_QSV_0_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_1_0 <= io_in_QSV_1_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_1_1 <= io_in_QSV_1_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_2_0 <= io_in_QSV_2_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_2_1 <= io_in_QSV_2_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_3_0 <= io_in_QSV_3_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      reg_3_1 <= io_in_QSV_3_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:326:22
      delay <= io_in_valid;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:327:22
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
      automatic logic [31:0] _RANDOM[0:4];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
        end	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
        reg_0_0 = _RANDOM[3'h0][15:0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
        reg_0_1 = _RANDOM[3'h0][31:16];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
        reg_1_0 = _RANDOM[3'h1][15:0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
        reg_1_1 = _RANDOM[3'h1][31:16];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
        reg_2_0 = _RANDOM[3'h2][15:0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
        reg_2_1 = _RANDOM[3'h2][31:16];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
        reg_3_0 = _RANDOM[3'h3][15:0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
        reg_3_1 = _RANDOM[3'h3][31:16];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
        delay = _RANDOM[3'h4][0];	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :327:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_QSV_0_0 = reg_0_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
  assign io_out_QSV_0_1 = reg_0_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
  assign io_out_QSV_1_0 = reg_2_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
  assign io_out_QSV_1_1 = reg_2_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
  assign io_out_QSV_2_0 = reg_1_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
  assign io_out_QSV_2_1 = reg_1_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
  assign io_out_QSV_3_0 = reg_3_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
  assign io_out_QSV_3_1 = reg_3_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :326:22
  assign io_out_valid = delay;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SingleGate.scala:318:7, :327:22
endmodule

module ChooseGate_2(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:18:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_in_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
                io_out_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:19:14
);

  SwapGate gate (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:30:22
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_0_0),
    .io_in_QSV_0_1  (io_in_QSV_0_1),
    .io_in_QSV_1_0  (io_in_QSV_1_0),
    .io_in_QSV_1_1  (io_in_QSV_1_1),
    .io_in_QSV_2_0  (io_in_QSV_2_0),
    .io_in_QSV_2_1  (io_in_QSV_2_1),
    .io_in_QSV_3_0  (io_in_QSV_3_0),
    .io_in_QSV_3_1  (io_in_QSV_3_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (io_out_QSV_0_0),
    .io_out_QSV_0_1 (io_out_QSV_0_1),
    .io_out_QSV_1_0 (io_out_QSV_1_0),
    .io_out_QSV_1_1 (io_out_QSV_1_1),
    .io_out_QSV_2_0 (io_out_QSV_2_0),
    .io_out_QSV_2_1 (io_out_QSV_2_1),
    .io_out_QSV_3_0 (io_out_QSV_3_0),
    .io_out_QSV_3_1 (io_out_QSV_3_1),
    .io_out_valid   (io_out_valid)
  );
endmodule

module SWGate2QubitVector16bit(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:38:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_in_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
                io_out_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:40:14
);

  ChooseGate_2 gate_0 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\Gates\\SpanVector.scala:44:53
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_0_0),
    .io_in_QSV_0_1  (io_in_QSV_0_1),
    .io_in_QSV_1_0  (io_in_QSV_1_0),
    .io_in_QSV_1_1  (io_in_QSV_1_1),
    .io_in_QSV_2_0  (io_in_QSV_2_0),
    .io_in_QSV_2_1  (io_in_QSV_2_1),
    .io_in_QSV_3_0  (io_in_QSV_3_0),
    .io_in_QSV_3_1  (io_in_QSV_3_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (io_out_QSV_0_0),
    .io_out_QSV_0_1 (io_out_QSV_0_1),
    .io_out_QSV_1_0 (io_out_QSV_1_0),
    .io_out_QSV_1_1 (io_out_QSV_1_1),
    .io_out_QSV_2_0 (io_out_QSV_2_0),
    .io_out_QSV_2_1 (io_out_QSV_2_1),
    .io_out_QSV_3_0 (io_out_QSV_3_0),
    .io_out_QSV_3_1 (io_out_QSV_3_1),
    .io_out_valid   (io_out_valid)
  );
endmodule

module NewMultCircuit0_06(	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:18:7
  input         clock,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:18:7
                reset,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:18:7
  input  [15:0] io_in_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_in_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_in_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_in_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_in_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_in_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_in_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_in_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
  input         io_in_valid,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
  output [15:0] io_out_QSV_0_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_out_QSV_0_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_out_QSV_1_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_out_QSV_1_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_out_QSV_2_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_out_QSV_2_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_out_QSV_3_0,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
                io_out_QSV_3_1,	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
  output        io_out_valid	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:21:14
);

  wire [15:0] _m_io_out_QSV_0_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
  wire [15:0] _m_io_out_QSV_0_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
  wire [15:0] _m_io_out_QSV_1_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
  wire [15:0] _m_io_out_QSV_1_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
  wire [15:0] _m_io_out_QSV_2_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
  wire [15:0] _m_io_out_QSV_2_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
  wire [15:0] _m_io_out_QSV_3_0;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
  wire [15:0] _m_io_out_QSV_3_1;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
  wire        _m_io_out_valid;	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
  HGate2QubitVector16bit m (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (io_in_QSV_0_0),
    .io_in_QSV_0_1  (io_in_QSV_0_1),
    .io_in_QSV_1_0  (io_in_QSV_1_0),
    .io_in_QSV_1_1  (io_in_QSV_1_1),
    .io_in_QSV_2_0  (io_in_QSV_2_0),
    .io_in_QSV_2_1  (io_in_QSV_2_1),
    .io_in_QSV_3_0  (io_in_QSV_3_0),
    .io_in_QSV_3_1  (io_in_QSV_3_1),
    .io_in_valid    (io_in_valid),
    .io_out_QSV_0_0 (_m_io_out_QSV_0_0),
    .io_out_QSV_0_1 (_m_io_out_QSV_0_1),
    .io_out_QSV_1_0 (_m_io_out_QSV_1_0),
    .io_out_QSV_1_1 (_m_io_out_QSV_1_1),
    .io_out_QSV_2_0 (_m_io_out_QSV_2_0),
    .io_out_QSV_2_1 (_m_io_out_QSV_2_1),
    .io_out_QSV_3_0 (_m_io_out_QSV_3_0),
    .io_out_QSV_3_1 (_m_io_out_QSV_3_1),
    .io_out_valid   (_m_io_out_valid)
  );
  SWGate2QubitVector16bit m_1 (	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
    .clock          (clock),
    .reset          (reset),
    .io_in_QSV_0_0  (_m_io_out_QSV_0_0),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
    .io_in_QSV_0_1  (_m_io_out_QSV_0_1),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
    .io_in_QSV_1_0  (_m_io_out_QSV_1_0),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
    .io_in_QSV_1_1  (_m_io_out_QSV_1_1),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
    .io_in_QSV_2_0  (_m_io_out_QSV_2_0),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
    .io_in_QSV_2_1  (_m_io_out_QSV_2_1),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
    .io_in_QSV_3_0  (_m_io_out_QSV_3_0),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
    .io_in_QSV_3_1  (_m_io_out_QSV_3_1),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
    .io_in_valid    (_m_io_out_valid),	// \\src\\main\\scala\\QunatumLayers\\ArithmiticGates\\GeneratePipline.scala:34:23
    .io_out_QSV_0_0 (io_out_QSV_0_0),
    .io_out_QSV_0_1 (io_out_QSV_0_1),
    .io_out_QSV_1_0 (io_out_QSV_1_0),
    .io_out_QSV_1_1 (io_out_QSV_1_1),
    .io_out_QSV_2_0 (io_out_QSV_2_0),
    .io_out_QSV_2_1 (io_out_QSV_2_1),
    .io_out_QSV_3_0 (io_out_QSV_3_0),
    .io_out_QSV_3_1 (io_out_QSV_3_1),
    .io_out_valid   (io_out_valid)
  );
endmodule

